<!-- js --><script src="js/catalog.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="js/jquery.min.js"></script>
<script src="js/jquery.lazy.min.js"></script>
<script src="js/jquery.lazy.plugins.min.js"></script>
<script src="js/jquery.inputmask.bundle.min.js"></script>
<script src="js/swiper-bundle.min.js"></script>
<script src="js/prefixfree.min.js"></script>
<script src="js/aos.js"></script>
<script src="js/sana.js"></script>
<script src="/telegramform/js/telegramform3.js"></script>
<script src="/telegramform/js/telegramform2.js"></script>
